import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getAllPosts } from "../utils/contentful.js";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [posts, setPosts] = useState<any>("");
  useEffect(() => {
    async function getPost() {
      try {
        const response = await getAllPosts();
        setPosts(response);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    }
    getPost();
  }, []);
  console.log("posts-", posts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <ol>
            {posts &&
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              posts.map(function (post: any) {
                const date = new Date(post.date).toLocaleDateString();
                return (
                  // eslint-disable-next-line react/jsx-key
                  <li>
                    <h3>{post.title}</h3>
                    <p>
                      Author: <b>{post.author}</b>, Date: <b>{date}</b>
                    </p>
                    <p>{post.body?.json?.content[0]?.content[0].value}</p>
                    <Image
                      className={styles.logo}
                      src={post.image?.url}
                      alt="Blog Image"
                      width={250}
                      height={250}
                      priority
                    />
                  </li>
                );
              })}
          </ol>
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
